GET http://localhost:3001/ HTTP/1.1

###

GET http://localhost:3001/utenti HTTP/1.1

###

GET http://localhost:3000/utenti/1 HTTP/1.1

###

POST http://localhost:3000/utenti HTTP/1.1
Content-Type: application/json

{
    "nome": "TIzio",
    "cognome": "Wonka"
}

###

DELETE http://localhost:3000/utenti/7 HTTP/1.1

###

PUT http://localhost:3000/utenti/1   HTTP/1.1
Content-Type: application/json

{
    "nome": "Paolo",
    "cognome": "Brambilla"
}

###